# Configuration file

# name: regulation 
# name: finance_user 
# name: finance_guilty
source_database:
  host: 192.168.0.164
  port: 15432
  name: dwd_pos_t90
  user: postgres
  password: 123456

target_database:
  host: 192.168.0.164
  port: 15432
  name: test
  user: postgres
  password: 123456

codetables:
  - barcode_type
  - item_nature
  - category_cn
  - brand_cn
  - fpc_size_segment_cn

# 设定字段不需要统计，直接按照规则生成，支持的规则包括
# 如果指定字段类型为 llm，则由大模型进行判断，确定该字段的类型。
specified_columns:
  store_dim_sample:
    - cust_id: name
    - province_name: province
    - city_name: city
    - district_name: district
    - store_address: street_address
    - regional_manager_email: email
    - premium_receiver: company
    - posm_receiver_phone: phone_number
    - posm_address: address
    - cust_id: user_name
  gtin_fpc_dim_sample:
    - cust_id:


